<a href="https://colab.research.google.com/github/andiunsia/DataScience_240401010009_Andi/blob/main/Pertemuan3_Andi_240401010009.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

---
Nama : Andi

NIM : 240401010009

Kelas : IF204

---

# **Latihan Pertemuan 3**

# 2. Import Library

In [ ]:
import pandas as pd
import numpy as np
from scipy.stats.mstats import winsorize
import requests
from pandas import json_normalize

# 3. Muat Dataset

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving housing_dirty.csv to housing_dirty.csv

In [ ]:
df = pd.read_csv('housing_dirty.csv')

# 4. Eksplorasi Awal

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            130 non-null    int64
 1   luas_m2       112 non-null    float64
 2   harga_juta    113 non-null    float64
 3   kota          130 non-null    object
 4   kamar         120 non-null    float64
 5   tahun_bangun  130 non-null    int64
 6   kondisi       130 non-null    object
dtypes: float64(3), int64(2), object(2)
memory usage: 7.2+ KB

In [ ]:
df.describe()

               id      luas_m2    harga_juta       kamar  tahun_bangun
count  130.000000   112.000000  1.130000e+02  120.000000    130.000000
mean    65.500000   267.627679  8.856325e+05    3.433333   2062.638462
std     37.671829   885.664181  9.407144e+06    1.776283    701.684043
min      1.000000   -50.000000 -5.000000e+02    1.000000   1890.000000
25%     33.250000    87.050000  3.450000e+02    2.000000   1991.250000
50%     65.500000   193.800000  6.550000e+02    4.000000   2002.000000
75%     97.750000   280.675000  9.550000e+02    5.000000   2011.750000
max    130.000000  9500.000000  1.000000e+08    6.000000   9999.000000

In [ ]:
df.isnull().sum()

id               0
luas_m2         18
harga_juta      17
kota             0
kamar           10
tahun_bangun     0
kondisi          0
dtype: int64

# 5. Hapus baris duplikat

In [ ]:
df.drop_duplicates(inplace=True)

# 6. Normalisasi string

In [ ]:
df['kota'] = df['kota'].str.strip().str.title()
df['kondisi'] = df['kondisi'].str.strip().str.lower()

# 7. Imputasi missing values

In [ ]:
#median untuk numerik, modus untuk kategorik

df['luas_m2'] = df['luas_m2'].fillna(df['luas_m2'].median())
df['harga_juta'] = df['harga_juta'].fillna(df['harga_juta'].median())
df['kamar'] = df['kamar'].fillna(df['kamar'].mode()[0])

# 8. Tangani outlier

In [ ]:
#IQR Fence pada kolom harga_juta dan luas_m2

for col in ['harga_juta', 'luas_m2', 'tahun_bangun']:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    df[col] = df[col].clip(Q1-1.5*IQR, Q3+1.5*IQR)

# 9. Validasi akhir

In [ ]:
assert df.isnull().sum().sum() == 0, 'Masih ada missing!'
assert df.duplicated().sum() == 0, 'Masih ada duplikat!'
print('Shape akhir:', df.shape)

Shape akhir: (130, 7)

# 10. Ekspor

In [ ]:
df.to_csv('housing_clean.csv', index=False)
print('Dataset bersih tersimpan!')

Dataset bersih tersimpan!

---
# **Kesimpulan**

**Data Cleaning dan Preprocessing**


Proses data cleaning pada dataset tujuannya adalah mengubah data mentah menjadi dataset yang bersih, konsisten, dan siap untuk analisis lebih lanjut. Mulai dari deteksi missing, penghapusan duplikat, normalisasi teks, hingga penanganan outlier, setiap langkah diterapkan dengan tepat sesuai karakteristik data. Proses ini menegaskan bahwa data cleaning adalah tahap krusial sebelum analisis atau pemodelan, karena kualitas data sangat memengaruhi validitas hasil akhir. Berikut tahapannya :

1.   Eksplorasi Awal (Data Inspection)

      Dari hasil inspeksi menggunakan info() dan describe()

2.   Penghapusan Duplikat

      Baris duplikat diidentifikasi dan dihapus menggunakan drop_duplicates(), memastikan setiap baris mewakili data unik.

3.   Normalisasi String (Konsistensi Format)

      Kolom kota diubah menjadi format Title Case (huruf pertama kapital) dan kolom kondisi menjadi lowercase menggunakan metode str.strip() dan str.title()/str.lower(). Hal ini menghilangkan spasi berlebih dan menyamakan format penulisan.

4.   Imputasi Missing Values

      Numerik: Kolom luas_m2 dan harga_juta diisi dengan nilai median (nilai tengah). Kolom kamar diisi dengan modus (nilai paling sering muncul).

      
5.   Penanganan Outlier

      Pada kolom harga_juta, luas_m2, dan tahun_bangun, nilai-nilai di luar batas lower dan upper (Q1 - 1.5×IQR dan Q3 + 1.5×IQR) dibatasi ke nilai batas tersebut agar dapat mempertahankan ukuran dataset (tidak menghapus baris) tetapi efektif terhadap pengaruh nilai yang ekstrem.

6.   Validasi Akhir

      Setelah seluruh tahapan, dilakukan validasi menggunakan assert untuk memastikan tidak ada lagi missing value dan baris duplikat.


7.   Ekspor Dataset Bersih

      Data bersih disimpan ke file housing_clean.csv untuk digunakan pada tahap analisis atau pemodelan selanjutnya.